// frontend-angular/src/app/component/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    console.log('Header launch call initiated');
  }
}


<div class="container"></div>
<div class="content " role="main">
   <!-- Highlight Card -->
   <div class="card highlight-card card-small">
      <div class="banner-card">
         <div class="container"></div>
         <header>
            <div>
               <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-between">
                  <img src="../../assets/img/mediscreen-logo.png" width="240" height="60" alt="Site logo" />
                  <form>
                     <input type=" search" placeholder="Search..." aria-label="Search" />
                     <button type="button"><i class="fas fa-search">🔎︎&nbsp;&nbsp;</i></button>&nbsp;&nbsp;&nbsp;&nbsp;
                  </form>
               </nav>

               
               <nav class="col navbar navbar-expand-lg navbar-dark bg-info font-weight-bold">
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
                     aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  </button>
                  <ul class="navbar-nav mx-auto ">
                     <li class="nav-item nav-link px-3"><a class="nav-link" href="/">Home</a>
                     </li>
                     <li class="nav-item nav-link px-3"><a class="nav-link" href="#">About</a>
                     </li>
                     <li class="nav-item nav-link px-3"><a class="nav-link" href="/patients">Services</a>
                     </li>
                     <li class="nav-item nav-link px-3"><a class="nav-link" href="#">Resources</a>
                     </li>
                     <li class="nav-item nav-link px-3"><a class="nav-link" href="#">News Blog</a>
                     </li>
                  </ul>
               </nav>
            </div>
         </header>
      </div>
   </div>
</div>

// frontend-react/src/components/HeaderComponent.js
import React, { Component } from 'react'
import mediscreenLogo from '../img/mediscreen-logo.png';

class HeaderComponent extends Component {
    constructor(props) {
        super(props)

        this.state = {
                 
        }
    }

    render() {
        return (
                            <div>
        <div className="container"></div>
                <header>

                <nav className="navbar navbar-light bg-light justify-content-between">

                <img src={mediscreenLogo} width="240" height="60" alt="Site logo"/>
                <form className="form-inline">
  

                        <input className="form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search"/>
                        <button className="btn btn-outline-success my-2 my-sm-0" type="button"><i className="fas fa-search">🔎︎</i></button>
                    </form>
                    </nav>
                </header>
            </div>
        )
    }
}

export default HeaderComponent
