// frontend-react/src/components/FooterComponent.jsx
import React, { Component } from 'react'

class FooterComponent extends Component {
    constructor(props) {
        super(props)

        this.state = {
                 
        }
    }

    render() {
        return (
            <div className="container bg-info text-dark">
			<div className="row pt-2 pb-0">


           { /*<div>
                <footer className = "footer">
                    <span className="text-muted">All Rights Reserved 2022 @OpenClassrooms</span>
                </footer>
           </div>*/}
            </div>
		</div>
        )
    }
}

export default FooterComponent

// frontend-angular/src/app/component/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    console.log('FOOTER call initiated');
  }
}

<!--<footer class="footer">
  <div class="container bg-info text-dark">
    <div class="row pt-2 pb-0">
      <span style="text-align: center; color: grey;">All Rights Reserved 2022 @OpenClassrooms</span>
    </div>
  </div>

</footer>-->
